FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry==1.8.4
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . .
CMD ["python", "consumer.py"]
